name: "Microbiome_Disease_Models"
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - python==3.9.12
  - pip
  - pip:
    - py4cytoscape==1.5.0
    - networkx==2.8.6
    - igraph==0.10.0
    - numpy==1.23.2
    - pandas==1.4.4
    - texttable==1.6.4


